import "./globals.css";

import UserProvider from "@/context/userContext";
import DoctorProvider from "@/context/doctorContext";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Raksha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased font-sans">
        <UserProvider>
          <DoctorProvider>
            {children}
            <ToastContainer position="top-right" autoClose={3000} />
          </DoctorProvider>
        </UserProvider>
      </body>
    </html>
  );
}